Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -14,49 +14,27 @@ pipeline {
         DOCKER_TAG = 'latest'
     }
 
+    stages {
+        stage('Setup Environment') {
+            steps {
+                sh '''
+                    echo "Checking and Installing AWS CLI and Docker..."
 
+                    if ! command -v aws &> /dev/null; then
+                        echo "Installing AWS CLI..."
+                        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+                        rm -rf aws
+                        unzip -o awscliv2.zip
+                        sudo ./aws/install
+                        rm -rf awscliv2.zip aws
+                    else
+                        echo "AWS CLI already installed."
+                    fi
 
-
-  stage('Setup Environment') {
-    steps {
-        sh '''
-            echo "Checking and Installing AWS CLI and Docker..."
-
-            # Check if AWS CLI is installed
-            if ! command -v aws &> /dev/null; then
-                echo "Installing AWS CLI..."
-                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-                rm -rf aws  # Remove any previous AWS installation directory
-                unzip -o awscliv2.zip  # Overwrite existing files without prompt
-                sudo ./aws/install
-                rm -rf awscliv2.zip aws
-            else
-                echo "AWS CLI already installed."
-            fi
-
-            # Verify AWS CLI installation
-            aws --version || { echo "AWS CLI installation failed"; exit 1; }
-
-            # Install Docker if not found
-            if ! command -v docker &> /dev/null; then
-                echo "Installing Docker..."
-                sudo apt update
-                sudo apt install -y ca-certificates curl gnupg
-                sudo install -m 0755 -d /etc/apt/keyrings
-                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
-                sudo chmod a+r /etc/apt/keyrings/docker.asc
-                echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-                sudo apt update
-                sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
-                sudo systemctl start docker
-                sudo systemctl enable docker
-            else
-                echo "Docker is already installed."
-            fi
-        '''
-    }
-}
-
+                    aws --version || { echo "AWS CLI installation failed"; exit 1; }
+                '''
+            }
+        }
 
         stage('Clone Repository') {
             steps {
